"""
TokenIntel launch helper:

1) Runs a local test report on SOL ($SOL)
2) Packages core agent code into a single Swarms uploadable script
3) Prints the exact Frenzy Mode URL and the Frenzy tokenization command
"""

from __future__ import annotations

import base64
import os
import sys
import zipfile
from pathlib import Path
from typing import Any


BASE_DIR = Path(__file__).resolve().parent
DEFAULT_SOL_MINT = "So11111111111111111111111111111111111111112"


def _choose_core_dir() -> Path:
    """
    Prefer repo root core files when present, otherwise fall back to tokenintel/.
    """
    root = BASE_DIR
    if (root / "agents.py").exists() and (root / "tools.py").exists() and (root / "models.py").exists():
        return root

    ti = BASE_DIR / "tokenintel"
    if (ti / "agents.py").exists() and (ti / "tools.py").exists() and (ti / "models.py").exists():
        return ti

    raise FileNotFoundError(
        "Could not find core files (agents.py/tools.py/models.py). Expected at repo root or tokenintel/."
    )


CORE_DIR = _choose_core_dir()


def run_local_test(sol_mint: str = DEFAULT_SOL_MINT) -> None:
    sys.path.insert(0, str(CORE_DIR))
    from config import reload_settings

    reload_settings()
    from models import ResearchDepth, ResearchRequest
    from agents import run_research

    print("Running local test report on $SOL ...")
    request = ResearchRequest(
        token_address=sol_mint,
        chain="solana",
        symbol_hint="SOL",
        include_social=True,
        include_onchain=True,
        depth=ResearchDepth.STANDARD,
    )

    result = run_research(request)
    if not getattr(result, "success", False) or getattr(result, "report", None) is None:
        raise RuntimeError(f"Local test failed: {getattr(result, 'error_message', None)}")

    report = result.report
    dist_dir = BASE_DIR / "dist"
    dist_dir.mkdir(parents=True, exist_ok=True)
    (dist_dir / "local_test_report.md").write_text(report.full_report_markdown, encoding="utf-8")

    print("Local test OK.")
    print(f"Token: ${report.token_symbol}  Name: {report.token_name or 'N/A'}")
    if report.onchain and report.onchain.price is not None:
        print(
            f"Price: ${report.onchain.price:.6f}  24h: {report.onchain.change_24h:+.2f}%"
            if report.onchain.change_24h is not None
            else f"Price: ${report.onchain.price:.6f}"
        )
    print(f"Sentiment score: {report.sentiment.score:+.2f}")
    print(f"Saved: {dist_dir / 'local_test_report.md'}")


def package_for_swarms() -> Path:
    """
    Build:
      - dist/swarms-agent.py (single-file script with embedded agents.py + tools.py)
      - dist/tokenintel_swarms_upload.zip (zip bundle for marketplace upload)
    """
    tools_path = CORE_DIR / "tools.py"
    agents_path = CORE_DIR / "agents.py"
    config_path = CORE_DIR / "config.py"
    models_path = CORE_DIR / "models.py"
    utils_path = CORE_DIR / "utils.py"
    req_path = CORE_DIR / "requirements.txt"

    for p in (tools_path, agents_path, config_path, models_path, utils_path, req_path):
        if not p.exists():
            raise FileNotFoundError(f"Missing required file: {p}")

    tools_b64 = base64.b64encode(tools_path.read_bytes()).decode("ascii")
    agents_b64 = base64.b64encode(agents_path.read_bytes()).decode("ascii")

    dist_dir = BASE_DIR / "dist"
    dist_dir.mkdir(parents=True, exist_ok=True)

    swarms_agent_path = dist_dir / "swarms-agent.py"
    swarms_agent_code = f'''\
from __future__ import annotations

import base64
import sys
import types
from typing import Any, Dict

# Auto-generated by TokenIntel launch_helper.py
# Embeds core tools.py + agents.py into a single swarms-agent script for Swarms upload.
# Companion files are included in tokenintel_swarms_upload.zip:
#   - config.py, models.py, utils.py, requirements.txt

_TOOLS_B64 = "{tools_b64}"
_AGENTS_B64 = "{agents_b64}"


def _decode(code_b64: str) -> str:
    return base64.b64decode(code_b64).decode("utf-8")


# Inject an in-memory "tools" module so embedded agents.py imports work unchanged.
_tools_mod = types.ModuleType("tools")
exec(_decode(_TOOLS_B64), _tools_mod.__dict__)
sys.modules["tools"] = _tools_mod

_agents_globals: Dict[str, Any] = {{}}
exec(_decode(_AGENTS_B64), _agents_globals)

run_research = _agents_globals.get("run_research")
list_registered_tools = _agents_globals.get("list_registered_tools")


def swarms_agent_run(payload: Dict[str, Any]) -> Dict[str, Any]:
    """
    Swarms-friendly entrypoint.

    payload is expected to match ResearchRequest:
      token_address, chain, symbol_hint, include_social, include_onchain, depth
    """
    if run_research is None:
        return {{"success": False, "error": "run_research not found in embedded agents.py"}}

    from models import ResearchRequest

    req = ResearchRequest(**payload)
    result = run_research(req)

    if getattr(result, "success", False) and getattr(result, "report", None) is not None:
        return result.report.model_dump(mode="json")

    return {{"success": False, "error": getattr(result, "error_message", "unknown error")}}
'''

    swarms_agent_path.write_text(swarms_agent_code, encoding="utf-8")

    zip_path = dist_dir / "tokenintel_swarms_upload.zip"
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.write(swarms_agent_path, arcname="swarms-agent.py")
        z.write(config_path, arcname="config.py")
        z.write(models_path, arcname="models.py")
        z.write(utils_path, arcname="utils.py")
        z.write(req_path, arcname="requirements.txt")

    print(f"Packaged for Swarms upload: {zip_path}")
    print(f"Single swarms-agent script: {swarms_agent_path}")
    return zip_path


def print_frenzy_launch_steps() -> None:
    frenzy_url = "https://swarms.world/launch?frenzy=true"
    print("\nFrenzy Mode URL:")
    print(frenzy_url)

    # Token Launch API (Frenzy):
    # - Requires SWARMS_API_KEY and SWARMS_CREATOR_PRIVATE_KEY in your shell environment.
    # - quote_mint SOL matches TokenIntel's current $SOL-oriented quote flow.
    token_cmd = (
        'curl.exe -Method POST "https://swarms.world/api/token/launch" '
        '-H "Authorization: Bearer $env:SWARMS_API_KEY" '
        '-H "Content-Type: application/json" '
        '-d ( @{ '
        'name="TokenIntel Research Agent"; '
        'description="TokenIntel ($TINTEL) — multi-agent Web3 research report generator (on-chain + market + social/news)."; '
        'ticker="TINTEL"; '
        'private_key="$env:SWARMS_CREATOR_PRIVATE_KEY"; '
        'fee_selection="frenzy"; '
        'quote_mint="SOL"; '
        '} | ConvertTo-Json -Compress )'
    )

    print("\nTokenization command (PowerShell, Frenzy):")
    print(token_cmd)


if __name__ == "__main__":
    try:
        run_local_test()
    except Exception as exc:
        print(f"Local test report failed: {exc}")
        print("Fix: set at least one LLM key (OPENAI_API_KEY/GROQ_API_KEY/ANTHROPIC_API_KEY) and ensure network access.")
        raise

    package_for_swarms()
    print_frenzy_launch_steps()

